### ISSUE TITLE
[IS Analytics] Authentication step listed as failure in local login attempts page 

### ISSUE THREAD

**Issue by dilin993** [wso2/analytics-solutions#102]
**Description:**
When a login is done through IS a step with failure is listed.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruwanta** [comment]
@dilin993 Will you be able to add more details please.
