### ISSUE TITLE
Left side pane does not collapse after selection of a page 

### ISSUE THREAD

**Issue by nandika** [wso2/analytics-solutions#107]
**Description:**
Left side pane does not collapse after selection of a page 

**Suggested Labels:**
EI Analytics dashboard
![sidepane](https://user-images.githubusercontent.com/2908631/45315567-60c0e480-b552-11e8-9993-39418fb0cfb5.png)

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by LakshanSS** [comment]
This issue has been solved in [this PR](https://github.com/wso2/carbon-dashboards/pull/1136).
