### ISSUE TITLE
[EI Analytics] Changes in chart types and widget titles

### ISSUE THREAD

**Issue by dilee** [wso2/analytics-solutions#108]
**Description:**
The following changes should be done in the EI analytics dashboard.

1. Following charts should be line charts. Bar charts are not suitable in this particular scenario.

<img width="1680" alt="screen shot 2018-09-11 at 12 33 39 am" src="https://user-images.githubusercontent.com/7193470/45318875-d1203380-b55b-11e8-95d4-3dbf11c635fd.png">

2. Widget titles should be changed as follows.
 "OVERALL EIAnalyticsTPS" -> "OVERALL TPS"
"[Overall Message Count]" -> "OVERALL MESSAGE COUNT"

Please refer to this [doc](https://docs.wso2.com/display/EI630/Monitoring+the+ESB+Profile+with+EI+Analytics#MonitoringtheESBProfilewithEIAnalytics-Step5-Analyzestatistics) for examples.

**Comment by isharailanga** [comment]
I'm working on this.

**Comment by erangatl** [comment]
Its better to avoid upper case for widget title and use title case.
