### ISSUE TITLE
[IS Analytics] Buttons and Text Fields are getting jumbled in widgets

### ISSUE THREAD

**Issue by ThisaruGuruge** [wso2/analytics-solutions#117]
**Description:**
> In `IS Analytics User Preferences` and `IS Analytics Login AttemptsMap` widgets, Buttons and the text input fields are getting jumbled when loading. [See attached screenshot]
>
> <img width="1680" alt="screen shot 2018-09-11 at 6 06 50 pm" src="https://user-images.githubusercontent.com/40016057/45365060-50b01000-b5f9-11e8-83e5-e7839e2378f8.png">
>
> This happens when the two widgets:
> * IsAnalyticsLoginAttemptsMap
> * IsAnalyticsUserPreferences
>
> are loaded. This is due to a naming conflict in `material-ui`. (Check related issue)

**Suggested Assignees:**
> @ThisaruGuruge 

**Steps to reproduce:**
> Create a dashboard with `IS Analytics User Preferences` widget and `IS Analytics Login Attempts Map` widget. 

**Related Issues:**
> https://github.com/marmelab/react-admin/issues/1782

**Comment by dilin993** [comment]
@ThisaruGuruge Is this issue still present? Have you guys identified a fix for this? If not, is there at least a work around?

**Comment by ThisaruGuruge** [comment]
Hi @dilin993 this issue still exists and we're working on a fix. Will update ASAP.
