### ISSUE TITLE
[EI Analytics] Overview > Request Count - Text mis-aligns with the Pie-chart

### ISSUE THREAD

**Issue by lasanthaS** [wso2/analytics-solutions#161]
**Description:**
In EI Analytics Overview page, Pie chart and its label mis-align in "Request Count" widget.

**Affected Product Version:**
WSO2SP 4.3.0

**Comment by LakshanSS** [comment]
This happened due to https://github.com/wso2/react-vizgrammar/issues/198 and was fixed in vizgrammar since 0.8.2. 
Can close this issue since we have upgraded to the latest vizgrammar.

![ghjg](https://user-images.githubusercontent.com/32201965/55146730-24aa4580-516b-11e9-80fb-6f075df831c9.png)
