### ISSUE TITLE
[APIM Analytics] Is Cassandra store supported ?

### ISSUE THREAD

**Issue by yhilem** [wso2/analytics-solutions#166]
Hi,
I want to change the store type to Cassandra.
Currently the store used is of type rdbms.

APIM 2.5.6 doc : https://docs.wso2.com/display/AM260/Configuring+APIM+Analytics#StandardSetup
The following is a list of database versions that are compatible with WSO2 API-M Analytics.
- Postgres 9.5 and later
- MySQL 5.6
- MySQL 5.7 
- Oracle 12c
- MS SQL Server 2012
- DB2

I want to change the @store(type = 'rdbms', datasource = 'APIM_ANALYTICS_DB') on all siddhi-files (https://github.com/wso2/analytics-solutions/tree/master/features/apim-analytics-feature/org.wso2.analytics.solutions.apim.analytics.feature/src/main/resources/siddhi-files) 

with a Store type Cassandra, but I did not find in the doc how to do : https://docs.wso2.com/display/SP430/Defining+Tables+for+Physical+Stores

There is a Cassandra implementation : https://github.com/wso2-extensions/siddhi-store-cassandra

![wso2-stream-processor-graphical-editor-http-message-trace-analytics-and-more-30-638](https://user-images.githubusercontent.com/13407261/46244380-9123d200-c3de-11e8-91c4-07420c343233.jpg)

Thanks 
Youcef HILEM

**Comment by Niveathika92** [comment]
Hi @yhilem,

As mentioned in the docs, we have not tested with the Cassandra store type for analytics solution scripts. However, on a higher level, the Siddhi apps use the same API to access the stores, with few modifications we may be able to change the store type. 

Casandra database cannot be defined as a WSO2 data source, however, we can define the store as a [reference](https://docs.wso2.com/display/SP430/Protecting+Sensitive+Data+via+the+Secure+Vault#ProtectingSensitiveDataviatheSecureVault-ProtectingsensitivedatainSiddhiapplications) and refer that in the siddhi apps. The properties used to define the Cassandra table type can be referred [here](https://wso2-extensions.github.io/siddhi-store-cassandra/api/1.0.8/#cassandra-store).

Please note, siddhi-store-cassandra is not packed in APIM analytics pack by default and needs to be added prior to this

Best Regards,
Niveathika

**Comment by Niveathika92** [comment]
Closing the issue as this is answered.
