### ISSUE TITLE
[EIAnalytics] EIAnalyticsHorizontalBarChart widget shows data only from the ''MINUTE'' aggregation

### ISSUE THREAD

**Issue by RolandHewage** [wso2/analytics-solutions#193]
**Description:**
"EIAnalyticsHorizontalBarChart" widget's fetch query is hardcoded to "minute" granularity although the Date Time Range Filter consists of a granularity selector.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 EI 6.4.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
1) Setup the Analytics profile of WSO2 Enterprise Integrator (WSO2 EI) 6.4.0 
2) Start the ESB profile & publish some data
3) Start the Analytics dashboard
4) Go to the Overview section
5) Notice that the horizontal barcharts of the Top Proxy Server by Request Count, Top APIs by Request Count, Top Endpoints by Request Count, Top Sequence by Request Count, Top Inbound Endpoint by Request Count sections doesn't change according to the interval (eg. hour, day, month) selected by the Date Time Range Filter.

**Related Issues:**
N/A

**Comment by Niveathika92** [comment]
Closing this as the fix is merged
