### ISSUE TITLE
[EI Analytics] Low throuput of EI Analytics Siddhi App with ESBEventTable Query disabled

### ISSUE THREAD

**Issue by shehan360** [wso2/analytics-solutions#204]
**Description:**
A low throughput of around 170 events a sec is observed for EI Analytics Siddhi app even with ESBEventTable Query disabled.

**Related Issues:**
#200

**Comment by shehan360** [comment]
Above PR improves the throughput to around 3800 events per sec.

**Comment by Niveathika92** [comment]
Closing as the above PR fixes the issue
