### ISSUE TITLE
[EI-Analytics] - EI_Analytics_StatApp.siddhi error when purging query 

### ISSUE THREAD

**Issue by ksdperera** [wso2/analytics-solutions#208]
**Description:**
In the following query 'time:dateSub(triggered_time, 2, 'week')' returns the String type, but its then evaluate in the delete on condition with the long type attribute 'ConfigEntryTable.eventTimestamp'

```
from    TablePurgingTriggerStream
select  time:dateSub(triggered_time, 2, 'week') as purgingTime
delete  ConfigEntryTable
on      ConfigEntryTable.eventTimestamp < purgingTime;
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2 EI Analytics-6.4

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1) wso2 EI Analytics-6.4 package (EI + Analytics worker)
2) EI_Analytics_StatApp.siddhi file is just "out of the box"; we use postgres for datasources
3) Error performing record deletion on table 'ConfigEntryTable': Batch entry 0 DELETE FROM ConfigEntryTable WHERE (ConfigEntryTable.eventTimestamp < '1548194400031' ) was aborted: ERROR: operator does not exist: bigint < character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Related Issues:**

**Comment by dnwick** [comment]
@ksdperera Can't we covert the value return from time:dateSub(triggered_time, 2, 'week') to long and use that stream for purging ?
