### ISSUE TITLE
[IS Analytics] Inaccurate merging of rows in RoleAggregation & AuthStat Aggregation tables as 'identityProviderType' not being used as a group by field

### ISSUE THREAD

**Issue by RolandHewage** [wso2/analytics-solutions#233]
**Description:**
There is a field called 'identityProviderType' in AuthStat Aggregation tables. This field gets a 'NULL' value in a single sign on situation while a user is already logged in from one app & try to login to another app. This field gets the value 'LOCAL' or 'FEDERATED' in other situations. The issue comes when data is persisted in higher level aggregation tables like hours, days, months etc... Where for a given username, serviceProvider, identityProvider, region, userStoreDomain, isFirstLogin fields which were the primary key fields there are situations where identityProviderType gets a value 'NULL' or something else & merge rows to form a single row which cause inaccurate counts. This is caused because 'identityProviderType' is not used as a group by field in SP based aggregation tables which was a primary key field in the identical old DAS based tables.

**Suggested Assignees:**
@RolandHewage 

**Affected Product Version:**
IS 5.6.0, IS Analytics 5.6.0 & IS 5.7.0, IS Analytics 5.7.0

**OS, DB, other environment details and versions:**    
MySQL 5.7.25
Java 1.8.0_191

**Steps to reproduce:**
1) Follow quick start guide related with IS 5.7.0 documentation
2) Select Single Sign On Scenario
3) Try 4 failure attempts to pickup-manager app
4) Make a successful login to pickup-dispatch app
5) Try single sign on by login pickup-manager app
6) See AuthStatAgg aggregation tables from SECONDS level to higher
7) The field identityProviderType gets NULL in a single sign on situation
8) This field gets an inaccurate value by merging rows in higher level aggregation tables

**Comment by Niveathika92** [comment]
Closing as this is Fixed
