### ISSUE TITLE
[IS Analytics] Overall Login Attempt Summary based on authStepSuccessCount eventhough it was implemented based on old DAS logic which uses authSuccessCount

### ISSUE THREAD

**Issue by RolandHewage** [wso2/analytics-solutions#234]
**Description:**
 The 'overall login attempt summary' in the new SP based IS Analytics dashboard is based on 'authStepSuccessCount'. But in a single sign on situation this field never increment eventhough its a login attempt made. In the old DAS based IS Analytics this was based on 'authSuccessCount'. This issue was clearly seen for identical use case scenarios tested on DAS & SP based  IS Analytics dashboards. They showed different counts. As in the definition it should be the final result of a collection of authentication steps (A collection of authentication steps is considered as an overall attempt). So in a multifactored authentication situation this 'Overall login attempt count should be incremented by one eventhough it passes a no. of steps in a single login attempt. 'authSuccessCount' field behave in such a manner.

**Suggested Assignees:**
@RolandHewage 

**Affected Product Version:**
IS 5.6.0, IS Analytics 5.6.0 & IS 5.7.0, IS Analytics 5.7.0

**OS, DB, other environment details and versions:**    
MySQL 5.7.25
Java 1.8.0_191

**Steps to reproduce:**
1) Follow the quickstart guide related with IS 5.6.0 & 5.7.0 documentation
2) Try out identical use case flows with IS Analytics 5.6.0 & IS Analytics 5.7.0 to generate an identical data set & compare the dashboard results shown for the same flow
3) They are different

**Comment by Niveathika92** [comment]
Closing as this is fixed by above PR
