### ISSUE TITLE
Add purging to the table in IS_ANALYTICS_AUTHENTICATION_OVERALL

### ISSUE THREAD

**Issue by ThisaruGuruge** [wso2/analytics-solutions#54]
**Description:**
> The siddhi app which is used to create data table does not have a purging method. Should add a trigger to purge the data in the table `OverallAuthenticationTable`

**Suggested Labels:**
> is-analytics, siddhi, purging

**Suggested Assignees:**
> @ThisaruGuruge

**Related Issues:**
> N/A

**Comment by Niveathika92** [comment]
Closing as the above PR fixes the issue
