### ISSUE TITLE
Issues in using siddhi geo extension within aggreagtions in SP Editor

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/analytics-solutions#61]
There is an issue when using (geo:) geo extension to get country and city from IP within an aggregation. The geo extension method like findCountryFromIP(<string> ip) can not be directly used with aggregations.

**Comment by Niveathika92** [comment]
The editor will not be packed and the issue can be solved using the following workaround,
Creating a temp stream before aggregation which has a variable got from using findCountryFromIP.

**Comment by Niveathika92** [comment]
Closing as this is not reproducible in SP 4.4.0-RC2
