### ISSUE TITLE
Remove redundant logic to reset data before database call

### ISSUE THREAD

**Issue by ThisaruGuruge** [wso2/analytics-solutions#72]
**Description:**
> In the analytic dashboard widgets, there was an issue, in which when the data is not returned from the database, the callback function was not executed in the `WidgetChannelManager`. This is now fixed and the redundant logic to reset data before the database call should be removed from the widgets. 

**Suggested Assignees:**
> @isharailanga @Ambujaa10

**Comment by Ambujaa10** [comment]
This issue is fixed for is-analytics.

**Comment by this** [comment]
Closing as per above comment.

**Comment by ThisaruGuruge** [comment]
This should be fixed for EI-Analytics too.
