### ISSUE TITLE
[IS Analytics] Two entries are seen in login attempts table per IS login

### ISSUE THREAD

**Issue by dilin993** [wso2/analytics-solutions#77]
**Description:**
There are two entries made in login attempts table for each IS login  

**Steps to reproduce:**

1) Configure IS to publish events.
2) Login from a SP

**Comment by ThisaruGuruge** [comment]
When I tried to reproduce this using the sample client, with just one event, it is working fine. If the dashboard is showing two entries for one login attempt, there might be two events coming from the IS side. Can you please check ?

**Comment by dilin993** [comment]
After looking into the issue we realized that this is not an issue. IS by default do a user login in several steps. And for each step there will be events published.
